name: CI/CD for Angular App

on:
  push:
    branches:
      - staging
      - master
    tags:
      - "v*1.*.*"  # Trigger for all version tags like v1.0.0, v2.1.0, etc.
      # - "v1.0.0"
      # commands to run tags -(git tag v1.0.0)
      # - (git push origin v1.0.0)        
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Trigger Source
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "Triggered by a tag: ${GITHUB_REF}"
          else
            echo "Triggered by a branch: ${GITHUB_REF}"
          fi

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build the project
        run: npm run build --if-present

      - name: Modify index.html based on branch or tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            sed -i 's|<base href="/">|<base href="/angular-staging/">|g' dist/test-angular/index.html
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            sed -i 's|<base href="/">|<base href="/angular-prod/">|g' dist/test-angular/index.html
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            sed -i 's|<base href="/">|<base href="/angular-prod/">|g' dist/test-angular/index.html
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/test-angular/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: /home/runner/work/test-angular/dist/test-angular/

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.STAGING_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to appropriate environment
        env:
          STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
          STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            sshpass -p $STAGING_PASSWORD scp -r /home/runner/work/test-angular/dist/test-angular/* $STAGING_USER@$STAGING_SERVER:public_html/angular-staging
          elif [ "${{ github.ref }}" == "refs/heads/master" ] || [[ "${{ github.ref }}" == refs/tags/* ]]; then
            sshpass -p $STAGING_PASSWORD scp -r /home/runner/work/test-angular/dist/test-angular/* $STAGING_USER@$STAGING_SERVER:public_html/angular-prod
          fi
